kind: pipeline
name: Build and Push Docker Image
trigger:
    branch:
        - main
    event:
        - push
platform:
    os: linux
    arch: amd64
environment:
    IMAGE_NAME: ${DRONE_REPO}
steps:
    - name: build and push Docker image
      image: plugins/docker
      settings:
          registry: ${REGISTRY}
          repo: benni347/portfolio
          auto_tag: true
          dockerfile: ./build/Dockerfile
          username: benni347
          password:
              from_secret: docker_password
      when:
          event: push
