kind: pipeline
name: Build and Push Docker Image
trigger:
    branch:
        - main
    event:
        - push
platform:
    os: linux
    arch: amd64
environment:
    IMAGE_NAME: ${DRONE_REPO}
steps:
    - name: checkout
      image: alpine/git
      commands:
          - git clone --depth=1 https://github.com/${DRONE_REPO}.git .
          - git checkout ${DRONE_COMMIT}
    - name: log in to the Container registry
      image: docker
      commands:
          - docker login -u ${DRONE_REPO_OWNER} -p ${DRONE_REPO_PRIVATE_TOKEN} ${REGISTRY}
      environment:
          DRONE_REPO_PRIVATE_TOKEN:
              from_secret: github_token
    - name: build and push Docker image
      image: plugins/docker
      settings:
          registry: ${REGISTRY}
          repo: ${REGISTRY}/${IMAGE_NAME}
          tags:
              - latest # or use a dynamic tag based on event or metadata
          auto_tag: true
          dockerfile: ./build/Dockerfile
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
      when:
          event: push
